import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from database import SessionLocal, Base, engine
from models import prospect, investor, project as project_module, template, learning, scouting, opportunity
from models.project import Project, ProjectTechnology, ProjectStage

db = SessionLocal()

# Clear existing auto-seeded data if any
db.query(Project).delete()
db.commit()

S = ProjectStage
T = ProjectTechnology

projects_data = [
    # ── VALECO ──────────────────────────────────────────────────────────────
    dict(code=1, name="Projet Éolien d'Argillières", developer_name="Valeco",
         technology=T.wind, technology_detail="Éolien terrestre", stage=S.permitting,
         capacity_mw=15.75, p50_mwh=22290, country="FR", region="Bourgogne-Franche-Comté",
         commune="Argillières", department="Haute-Saône", department_code="70",
         rtb_date="Q4 2026", cod_date="Q4 2027",
         permit_status="purgé", permit_type="ICPE", land_secured=True,
         grid_operator="RTE", offtake_type="AO CRE PPE2 (CR/FIP)",
         status_detail="(5) Raccordement au réseau — Permis purgé (CAA confirmé) + PTF signée"),

    # ── VIRIDI ──────────────────────────────────────────────────────────────
    dict(code=14, name="La Berre", developer_name="Viridi",
         technology=T.solar, technology_detail="AgriPV", stage=S.development,
         capacity_mw=10.7, p50_mwh=18766, country="FR", region="Auvergne-Rhône-Alpes",
         commune="Drôme", department="Drôme", department_code="26",
         rtb_date="Q4 2027", cod_date="Q4 2028",
         permit_status="à déposer", permit_type="PC", land_secured=True,
         grid_operator="Enedis", grid_connection_cost=1120000, offtake_type="AO CRE",
         status_detail="Mid-(3) Environnement & (4) Autorisations — Land secured, permit application planned Q2 2026"),

    dict(code=15, name="Les Brissaudières", developer_name="Viridi",
         technology=T.solar, technology_detail="AgriPV", stage=S.development,
         capacity_mw=15.5, p50_mwh=19185, country="FR", region="Centre-Val de Loire",
         commune="Lignières-de-Touraine / Azay-le-Rideau", department="Indre-et-Loire", department_code="37",
         rtb_date="Q4 2028", cod_date="Q4 2029",
         permit_status="à déposer", permit_type="PC", land_secured=True,
         grid_operator="Enedis", offtake_type="AO CRE",
         status_detail="Early-(3) Environment & (5) Grid connection — Land fully secured; EIA ongoing; PRAC in progress"),

    dict(code=16, name="Les Doranchères", developer_name="Viridi",
         technology=T.solar, technology_detail="AgriPV", stage=S.development,
         capacity_mw=22.4, p50_mwh=26400, country="FR", region="Centre-Val de Loire",
         commune="Vallères", department="Indre-et-Loire", department_code="37",
         rtb_date="Q4 2028", cod_date="Q4 2029",
         permit_status="à déposer", permit_type="PC", land_secured=True,
         grid_operator="Enedis", offtake_type="AO CRE",
         status_detail="Early-(3) Environment & (5) Grid connection — Land fully secured; EIA ongoing; grid + hybrid storage in progress"),

    dict(code=17, name="Les Forges", developer_name="Viridi",
         technology=T.solar, technology_detail="AgriPV", stage=S.development,
         capacity_mw=1.0, p50_mwh=1347, country="FR", region="Centre-Val de Loire",
         commune="Saint-Benoît-la-Forêt", department="Indre-et-Loire", department_code="37",
         rtb_date="Q1 2027", cod_date="Q1 2028",
         permit_status="à déposer", permit_type="DP", land_secured=True,
         grid_operator="Enedis", offtake_type="AO CRE ou S25",
         status_detail="Mid-(3) Environment & (4) Permitting — EIA exemption obtained; wetland diagnostic ongoing"),

    dict(code=18, name="Saint-Sauveur", developer_name="Viridi",
         technology=T.solar, technology_detail="Sol", stage=S.development,
         capacity_mw=7.0, p50_mwh=8553, country="FR", region="Bretagne",
         commune="Saint-Sauveur-des-Landes", department="Ille-et-Vilaine", department_code="35",
         rtb_date="Q1 2028", cod_date="Q1 2029",
         permit_status="à déposer", permit_type="PC", land_secured=True,
         grid_operator="Enedis", offtake_type="AO CRE",
         status_detail="Mid-(3) Environment — Land fully secured (13 ha); EIA exemption request under prep"),

    # ── ECODD ───────────────────────────────────────────────────────────────
    dict(code=19, name="CER", developer_name="Ecodd",
         technology=T.solar, technology_detail="Sol", stage=S.permitting,
         capacity_mw=3.01, country="FR",
         permit_status="déposé", permit_type="PC", land_secured=True,
         grid_operator="Enedis", grid_connection_cost=400000, offtake_type="AO CRE",
         rtb_date="Q3 2026", cod_date="Q1 2027",
         status_detail="Advanced-(4) PC déposé 12/10/2025, obtention prévue 07/2026"),

    dict(code=20, name="Up", developer_name="Ecodd",
         technology=T.solar, technology_detail="Sol", stage=S.permitting,
         capacity_mw=1.508, country="FR",
         permit_status="recours", permit_type="PC", land_secured=True,
         grid_operator="Enedis", grid_connection_cost=329741, offtake_type="AO CRE",
         status_detail="Nearly secured-(4) Statut Recours"),

    dict(code=21, name="SPT", developer_name="Ecodd",
         technology=T.solar, technology_detail="Sol", stage=S.ready_to_build,
         capacity_mw=3.0, country="FR",
         permit_status="purgé", permit_type="PC", land_secured=True,
         grid_operator="Enedis", grid_connection_cost=601770, offtake_type="AO CRE",
         status_detail="Secured-(7) RTB — Permis purgé + Certificat Enedis 11/17/2025 + PRAC"),

    dict(code=22, name="Saint-Denis-Catus", developer_name="Ecodd",
         technology=T.solar, technology_detail="Sol", stage=S.permitting,
         capacity_mw=4.0, country="FR",
         permit_status="déposé", permit_type="PC", land_secured=True,
         grid_operator="Enedis", grid_connection_cost=970000, offtake_type="AO CRE",
         rtb_date="Q3 2026", cod_date="Q1 2027",
         status_detail="Advanced-(4) PC déposé 04/2025, obtention prévue 07/2026"),

    dict(code=23, name="VIV", developer_name="Ecodd",
         technology=T.solar, technology_detail="Sol", stage=S.permitting,
         capacity_mw=13.0, country="FR",
         permit_status="déposé", permit_type="PC", land_secured=True,
         grid_connection_cost=2500000, offtake_type="PPA",
         rtb_date="Q4 2026", cod_date="Q2 2027",
         status_detail="Advanced-(4) PC déposé, purge prévue 09/2026"),

    dict(code=24, name="LGC", developer_name="Ecodd",
         technology=T.solar, technology_detail="Sol", stage=S.permitting,
         capacity_mw=13.5, country="FR",
         permit_status="déposé", permit_type="PC", land_secured=True,
         grid_operator="Enedis", grid_connection_cost=1931152, offtake_type="AO CRE",
         rtb_date="Q3 2026", cod_date="Q1 2027",
         notes="Ecodd 50% / EDF 50%",
         status_detail="Advanced-(4) PC déposé, obtention prévue 07/2026"),

    dict(code=25, name="LBP", developer_name="Ecodd",
         technology=T.solar, technology_detail="Sol", stage=S.permitting,
         capacity_mw=5.1, country="FR",
         permit_status="purgé", permit_type="PC", land_secured=True,
         grid_operator="Enedis", grid_connection_cost=1210430, offtake_type="AO CRE",
         status_detail="Secured-(5) Permis purgé 12/2025 + PRAC"),

    dict(code=26, name="Bord", developer_name="Ecodd",
         technology=T.solar, technology_detail="Sol", stage=S.permitting,
         capacity_mw=8.583, country="FR",
         permit_status="déposé", permit_type="PC", land_secured=True,
         grid_operator="Enedis", grid_connection_cost=888425, offtake_type="AO CRE",
         rtb_date="Q4 2026", cod_date="Q2 2027",
         status_detail="Advanced-(4) PC déposé 10/30/2025, obtention 06/2026, purge 08/2026"),

    dict(code=27, name="Gag", developer_name="Ecodd",
         technology=T.solar, technology_detail="Sol", stage=S.permitting,
         capacity_mw=2.01, country="FR",
         permit_status="recours", permit_type="PC", land_secured=True,
         grid_operator="Enedis", grid_connection_cost=458319, offtake_type="AO CRE",
         status_detail="Nearly secured-(4) Statut Recours"),

    dict(code=28, name="Qui", developer_name="Ecodd",
         technology=T.solar, technology_detail="Sol", stage=S.permitting,
         capacity_mw=24.0, country="FR",
         permit_status="déposé", permit_type="PC", land_secured=True,
         grid_operator="Enedis", grid_connection_cost=4900000, offtake_type="AO CRE",
         rtb_date="Q3 2026", cod_date="Q1 2027",
         notes="Ecodd 50% / Régie élec 50%",
         status_detail="Advanced-(4) PC déposé 11/10/2023, obtention prévue 07/2026"),

    # ── ADEN ────────────────────────────────────────────────────────────────
    dict(code=29, name="Saint-Denis-de-Jouhet", developer_name="ADEN",
         technology=T.solar, technology_detail="AgriPV Trackers", stage=S.development,
         capacity_mw=10.0, country="FR", region="Centre-Val de Loire",
         department="Indre", department_code="36",
         rtb_date="Q2 2028", cod_date="Q4 2028",
         permit_status="à déposer", permit_type="PC", land_secured=True,
         offtake_type="AO CfD ~0,07-0,08 €/kWh",
         status_detail="Early — Bail signé, PC à déposer. AgriPV Cow / Trackers"),

    dict(code=30, name="Capian", developer_name="ADEN",
         technology=T.solar, technology_detail="AgriPV Trackers", stage=S.development,
         capacity_mw=5.0, country="FR", region="Nouvelle-Aquitaine",
         department="Gironde", department_code="33",
         rtb_date="Q2 2028", cod_date="Q4 2028",
         permit_status="à déposer", permit_type="PC", land_secured=True,
         offtake_type="AO CfD ~0,07-0,08 €/kWh",
         status_detail="Early — Bail signé, PC à déposer. AgriPV Sheep / Viticole"),

    dict(code=31, name="Cusset", developer_name="ADEN",
         technology=T.solar, technology_detail="AgriPV Trackers", stage=S.development,
         capacity_mw=12.0, country="FR", region="Auvergne-Rhône-Alpes",
         department="Allier", department_code="03",
         rtb_date="Q2 2028", cod_date="Q1 2029",
         permit_status="à déposer", permit_type="PC", land_secured=True,
         offtake_type="AO CfD ~0,07-0,08 €/kWh",
         status_detail="Early — Bail signé, PC à déposer. AgriPV Sheep / Trackers"),

    dict(code=32, name="Saint-Jeannet", developer_name="ADEN",
         technology=T.solar, technology_detail="Sol Trackers", stage=S.development,
         capacity_mw=20.0, country="FR", region="Provence-Alpes-Côte d'Azur",
         department="Alpes-de-Haute-Provence", department_code="04",
         rtb_date="Q2 2029", cod_date="Q2 2030",
         permit_status="à déposer", permit_type="PC", land_secured=True,
         offtake_type="AO CfD ~0,07-0,08 €/kWh",
         status_detail="Early — Bail signé, PC à déposer. Fix + Trackers"),

    # ── NOVABRIDGE ──────────────────────────────────────────────────────────
    dict(code=33, name="Pr1 – Genouillac", developer_name="Novabridge",
         technology=T.solar, technology_detail="AgriPV Toiture", stage=S.ready_to_build,
         capacity_mw=0.10, country="FR",
         commune="Genouillac", department="Creuse", department_code="23",
         permit_status="purgé", permit_type="PC", land_secured=True,
         offtake_type="AO CRE",
         status_detail="PC purgé, bail 30 ans"),

    dict(code=34, name="Pr2 – Albon-d'Ardèche", developer_name="Novabridge",
         technology=T.solar, technology_detail="AgriPV Toiture", stage=S.ready_to_build,
         capacity_mw=0.29, country="FR",
         commune="Albon-d'Ardèche", department="Ardèche", department_code="07",
         permit_status="purgé", permit_type="PC", land_secured=True,
         offtake_type="AO CRE",
         status_detail="PC purgé, bail 30 ans"),

    dict(code=35, name="Pr3 – Arbois-en-Bugey", developer_name="Novabridge",
         technology=T.solar, technology_detail="AgriPV Toiture", stage=S.ready_to_build,
         capacity_mw=0.20, country="FR",
         commune="Arbois-en-Bugey", department="Ain", department_code="01",
         permit_status="purgé", permit_type="PC", land_secured=True,
         offtake_type="AO CRE",
         status_detail="PC purgé, bail 30 ans"),

    dict(code=36, name="Pr4 – Meilhards", developer_name="Novabridge",
         technology=T.solar, technology_detail="AgriPV Toiture", stage=S.ready_to_build,
         capacity_mw=0.50, country="FR",
         commune="Meilhards", department="Corrèze", department_code="19",
         permit_status="purgé", permit_type="PC", land_secured=True,
         offtake_type="AO CRE",
         status_detail="PC purgé, bail 30 ans"),

    dict(code=37, name="Pr5 – Carignan", developer_name="Novabridge",
         technology=T.solar, technology_detail="AgriPV Toiture", stage=S.ready_to_build,
         capacity_mw=0.35, country="FR",
         commune="Carignan", department="Ardennes", department_code="08",
         permit_status="purgé", permit_type="PC", land_secured=True,
         offtake_type="AO CRE",
         status_detail="PC purgé, bail 30 ans"),

    dict(code=38, name="Pr6 – Fromy", developer_name="Novabridge",
         technology=T.solar, technology_detail="AgriPV Toiture", stage=S.ready_to_build,
         capacity_mw=0.40, country="FR",
         commune="Fromy", department="Ardennes", department_code="08",
         permit_status="purgé", permit_type="PC", land_secured=True,
         offtake_type="AO CRE",
         status_detail="PC purgé, bail 30 ans"),

    dict(code=39, name="Pr7 – Crest", developer_name="Novabridge",
         technology=T.solar, technology_detail="AgriPV Toiture", stage=S.ready_to_build,
         capacity_mw=0.25, country="FR",
         commune="Crest", department="Drôme", department_code="26",
         permit_status="purgé", permit_type="PC", land_secured=True,
         offtake_type="AO CRE",
         status_detail="PC purgé, bail 30 ans"),

    dict(code=40, name="Pr8 – Canet-de-Salars", developer_name="Novabridge",
         technology=T.solar, technology_detail="AgriPV Toiture", stage=S.ready_to_build,
         capacity_mw=0.20, country="FR",
         commune="Canet-de-Salars", department="Aveyron", department_code="12",
         permit_status="purgé", permit_type="PC", land_secured=True,
         offtake_type="AO CRE",
         status_detail="PC purgé, bail 30 ans"),

    dict(code=41, name="Pr9 – Saint-Julien-aux-Bois", developer_name="Novabridge",
         technology=T.solar, technology_detail="AgriPV Toiture", stage=S.ready_to_build,
         capacity_mw=0.20, country="FR",
         commune="Saint-Julien-aux-Bois", department="Corrèze", department_code="19",
         permit_status="purgé", permit_type="PC", land_secured=True,
         offtake_type="AO CRE",
         status_detail="PC purgé, bail 30 ans"),

    dict(code=42, name="Pr10 – Val d'Oire et Gartempe", developer_name="Novabridge",
         technology=T.solar, technology_detail="AgriPV Toiture", stage=S.ready_to_build,
         capacity_mw=0.50, country="FR",
         commune="Val d'Oire et Gartempe", department="Haute-Vienne", department_code="87",
         permit_status="purgé", permit_type="PC", land_secured=True,
         offtake_type="AO CRE",
         status_detail="PC purgé, bail 30 ans"),

    # ── RECURRENT ENERGY ────────────────────────────────────────────────────
    dict(code=43, name="Reterre", developer_name="Recurrent Energy",
         technology=T.solar, technology_detail="AgriPV Sol Tracker 2P", stage=S.development,
         capacity_mw=20.0, country="FR",
         department="Creuse", department_code="23",
         rtb_date="Q4 2029", cod_date="Q2 2032",
         permit_status="à déposer", permit_type="PC", land_secured=True,
         grid_connection_cost=2571001, offtake_type="AO CRE",
         notes="Élevage bovin",
         status_detail="Early — Bail signé, PC à déposer. Élevage bovin"),

    dict(code=44, name="Condat", developer_name="Recurrent Energy",
         technology=T.solar, technology_detail="AgriPV Sol Tracker 2P", stage=S.development,
         capacity_mw=15.0, country="FR",
         department="Corrèze", department_code="19",
         rtb_date="Q1 2030", cod_date="Q3 2032",
         permit_status="à déposer", permit_type="PC", land_secured=True,
         grid_connection_cost=1917700, offtake_type="AO CRE",
         notes="Élevage bovin",
         status_detail="Early — Bail signé, PC à déposer. Élevage bovin"),

    dict(code=45, name="Saint-Romain", developer_name="Recurrent Energy",
         technology=T.solar, technology_detail="AgriPV Sol Tracker 2P", stage=S.development,
         capacity_mw=12.7, country="FR",
         department="Charente", department_code="16",
         rtb_date="Q3 2030", cod_date="Q1 2033",
         permit_status="à déposer", permit_type="PC", land_secured=True,
         grid_connection_cost=1630609, offtake_type="AO CRE",
         notes="Élevage caprin",
         status_detail="Early — Bail signé, PC à déposer. Élevage caprin"),

    dict(code=46, name="Peyrusse-Grande", developer_name="Recurrent Energy",
         technology=T.solar, technology_detail="AgriPV Sol Tracker 2P", stage=S.development,
         capacity_mw=15.0, country="FR",
         department="Gers", department_code="32",
         rtb_date="Q3 2030", cod_date="Q1 2033",
         permit_status="à déposer", permit_type="PC", land_secured=True,
         grid_connection_cost=1932685, offtake_type="AO CRE",
         notes="Élevage bovin",
         status_detail="Early — Bail signé, PC à déposer. Élevage bovin"),

    dict(code=47, name="Peyrusse-Vieille", developer_name="Recurrent Energy",
         technology=T.solar, technology_detail="AgriPV Sol Tracker 2P", stage=S.development,
         capacity_mw=13.0, country="FR",
         department="Gers", department_code="32",
         rtb_date="Q2 2029", cod_date="Q4 2031",
         permit_status="à déposer", permit_type="PC", land_secured=True,
         grid_connection_cost=1065682, offtake_type="AO CRE",
         notes="Mixte",
         status_detail="Early — Bail signé, PC à déposer. Mixte"),

    dict(code=48, name="Bouix", developer_name="Recurrent Energy",
         technology=T.solar, technology_detail="AgriPV Sol Tracker 2P", stage=S.development,
         capacity_mw=20.0, country="FR",
         department="Côte-d'Or", department_code="21",
         rtb_date="Q3 2029", cod_date="Q1 2032",
         permit_status="à déposer", permit_type="PC", land_secured=True,
         grid_connection_cost=2338855, offtake_type="AO CRE",
         notes="Élevage bovin",
         status_detail="Early — Bail signé, PC à déposer. Élevage bovin"),

    dict(code=49, name="Viersat", developer_name="Recurrent Energy",
         technology=T.solar, technology_detail="AgriPV Sol Tracker 2P", stage=S.development,
         capacity_mw=10.0, country="FR",
         department="Creuse", department_code="23",
         rtb_date="Q3 2028", cod_date="Q1 2031",
         permit_status="à déposer", permit_type="PC", land_secured=True,
         grid_connection_cost=1421491, offtake_type="AO CRE",
         notes="Élevage bovin",
         status_detail="Early — Bail signé, PC à déposer. Élevage bovin"),

    dict(code=50, name="Sury", developer_name="Recurrent Energy",
         technology=T.solar, technology_detail="AgriPV Sol Tracker 2P", stage=S.development,
         capacity_mw=9.77, country="FR",
         department="Cher", department_code="18",
         rtb_date="Q1 2028", cod_date="Q1 2031",
         permit_status="à déposer", permit_type="PC", land_secured=True,
         grid_connection_cost=1249232, offtake_type="AO CRE",
         notes="Élevage bovin",
         status_detail="Early — Bail signé, PC à déposer. Élevage bovin"),

    # ── RENERGIES ───────────────────────────────────────────────────────────
    dict(code=51, name="PR_FR_0124", developer_name="Renergies",
         technology=T.solar, technology_detail="AgriPV Sol", stage=S.development,
         capacity_mw=12.15, country="FR",
         department="Gard", department_code="30",
         rtb_date="Q1 2027", cod_date="Q1 2029",
         permit_status="à déposer", permit_type="PC", land_secured=True,
         offtake_type="AO CRE",
         notes="Livestock farming",
         status_detail="3. Etudes environnementales"),

    dict(code=52, name="PR_FR_0019", developer_name="Renergies",
         technology=T.solar, technology_detail="AgriPV Sol", stage=S.development,
         capacity_mw=7.18, country="FR",
         department="Maine-et-Loire", department_code="49",
         rtb_date="Q1 2027", cod_date="Q1 2028",
         permit_status="à déposer", permit_type="PC", land_secured=True,
         offtake_type="AO CRE",
         notes="Livestock farming",
         status_detail="3. Etudes environnementales"),

    dict(code=53, name="PR_FR_0029", developer_name="Renergies",
         technology=T.solar, technology_detail="AgriPV Sol", stage=S.development,
         capacity_mw=16.6, country="FR",
         department="Allier", department_code="03",
         rtb_date="Q1 2027", cod_date="Q1 2029",
         permit_status="à déposer", permit_type="PC", land_secured=True,
         offtake_type="AO CRE",
         notes="Livestock farming",
         status_detail="3. Etudes environnementales"),

    dict(code=54, name="PR_FR_0022", developer_name="Renergies",
         technology=T.solar, technology_detail="AgriPV Sol", stage=S.development,
         capacity_mw=5.5, country="FR",
         department="Isère", department_code="38",
         rtb_date="Q1 2027", cod_date="Q1 2028",
         permit_status="à déposer", permit_type="PC", land_secured=True,
         offtake_type="AO CRE",
         notes="Livestock farming",
         status_detail="3. Etudes environnementales"),

    dict(code=55, name="PR_FR_0020", developer_name="Renergies",
         technology=T.solar, technology_detail="AgriPV Sol", stage=S.development,
         capacity_mw=4.07, country="FR",
         department="Allier", department_code="03",
         rtb_date="Q1 2027", cod_date="Q1 2028",
         permit_status="à déposer", permit_type="PC", land_secured=True,
         offtake_type="AO CRE",
         notes="Livestock farming",
         status_detail="3. Etudes environnementales"),

    dict(code=56, name="PR_FR_0021", developer_name="Renergies",
         technology=T.solar, technology_detail="AgriPV Sol", stage=S.development,
         capacity_mw=10.74, country="FR",
         department="Rhône", department_code="69",
         rtb_date="Q1 2027", cod_date="Q1 2028",
         permit_status="à déposer", permit_type="PC", land_secured=True,
         offtake_type="AO CRE",
         notes="Livestock farming",
         status_detail="3. Etudes environnementales"),

    dict(code=57, name="PR_FR_0025", developer_name="Renergies",
         technology=T.solar, technology_detail="AgriPV Sol", stage=S.development,
         capacity_mw=4.92, country="FR",
         department="Gard", department_code="30",
         rtb_date="Q1 2027", cod_date="Q1 2029",
         permit_status="à déposer", permit_type="PC", land_secured=True,
         offtake_type="AO CRE",
         notes="Livestock farming",
         status_detail="3. Etudes environnementales"),
]

for data in projects_data:
    p = Project(**data)
    db.add(p)

db.commit()
db.close()

print(f"✅ {len(projects_data)} projets insérés avec succès.")
